# Generated by Django 2.2.12 on 2023-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TomaDeMuestra', models.DateField(blank=True)),
                ('Recepcion', models.DateField(blank=True)),
                ('NumeroDeLaminas', models.IntegerField(blank=True)),
                ('Tincion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Edad', models.IntegerField(null=True)),
                ('Medico', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('Muestra', models.CharField(max_length=200)),
                ('Diagnostico', models.CharField(max_length=100)),
            ],
        ),
    ]
