# Generated by Django 2.2.12 on 2023-02-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_muestra_pacientegenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MuestraInforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Muestra')),
                ('PacienteInforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.PacienteGenerales')),
            ],
        ),
    ]
