# Generated by Django 4.1.7 on 2023-03-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_nombre_pacientegenerales_nombres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadDeMuestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calidad', models.CharField(choices=[('SAT1', 'Satisfactorio para valoración citológica: con presencia de células epiteliales de la zona de transformación'), ('INSAT1', 'Insatisfactorio por ausencia de células exocervicales'), ('INSAT2', 'Insatisfactorio por presencia de escasas células exocervicales'), ('INSAT3', 'Insatisfactorio por más del 75% de células cubiertas por hematies'), ('INSAT4', 'Insatisfactorio por más del 75% de células cubiertas por inflamación'), ('INSAT5', 'Insatisfactorio por más del 75% de células cubiertas por hematies e inflamación')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CelEscamosas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escamosas', models.CharField(choices=[('ASC-US', 'De significado indeterminado(ASC-US)'), ('ASC-H', 'No puede excluirse HSIL(ASC-H)'), ('L-SIL', 'Lesión intraepitelial escamosa de bajo grado(L-SIL)'), ('H-SIL', 'Lesión intraepitelial escamosa de alto grado(H-SIL)'), ('L-SIL2', 'Lesión intraepitelial escamosa de bajo grado(L-SIL) con cambios sugestivos de HPV'), ('CAR', 'Carcinoma epirdermoide')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelGlandulares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Glandulares', models.CharField(choices=[('AT', 'Cel. gland. atipicas (CGA)'), ('AT2', 'Cel. gland. atipicas sugestivas de neoplasia'), ('AD', 'Adenocarcinoma')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(default='000-X', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conclusion', models.CharField(choices=[('CONCL1', 'Negativo para lesión intraepitelial o malignidad'), ('CONCL2', 'Anomalía de células epiteliales'), ('CONCL3', 'Positivo para lesión intraepitelial'), ('CONCL4', 'Positivo para neoplasia maligna')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioMicroscopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(choices=[('OPT1', 'Extendido citológico convencional exo-endocervical'), ('OPT2', 'Extendido citológico post-histectomia')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionHormonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluacion', models.CharField(choices=[('PAT', 'Patron concordante con historia'), ('TROF', 'Trofico'), ('HIP', 'Hipotrofico'), ('ATRO', 'Atrofico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FechaPie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallazgosNoNeoplasicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoNeoplasicos', models.CharField(choices=[('OPT1', 'Cambios celulares reactivos a la inflamación'), ('OPT2', 'Metaplasia escamosa'), ('OPT3', 'Metaplasia tubárica'), ('OPT4', 'Alteraciones atrófica'), ('OPT5', 'Alteraciones celulares secundarias a radioterapia'), ('OPT6', 'Alteraciones celulares secundarias a quimioterapia'), ('OPT7', 'Alteraciones celulares secundarias a DIUI')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inflamacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inflamation', models.CharField(choices=[('LEV', 'Leve'), ('MOD', 'Moderada'), ('SEV', 'Severa'), ('MOD2', 'Moderada-hemorragico'), ('MOD3', 'Severa-hemorragico')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugar', models.CharField(choices=[('LP', 'La Paz'), ('EA', 'El Alto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Microrganismos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Microrgs', models.CharField(choices=[('FLORA', 'Flora habitual'), ('FLORAB', 'Flora bacteriana mixta'), ('FLORAC', 'Flora cocoide'), ('CAMB', 'Cambios en la flora sugestivos de vaginosis bacteriana'), ('TRICO', 'Trichonomas vaginalis'), ('ORG', 'Organismos micóticos morfologicamente compatibles con candida SP.'), ('BACT', 'Bacterias morfologicamente compatibles con Actynomices SP.'), ('CAMB2', 'Cambios compatibles con virus herpes simple')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recomendacion', models.CharField(default='Sin descripcion', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='matricula',
            field=models.CharField(default='CCC-00000', max_length=50),
        ),
        migrations.CreateModel(
            name='InformeCito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalidadDeMuestraInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.calidaddemuestra')),
                ('CelEscamosasInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.celescamosas')),
                ('CelGlandularesInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.celglandulares')),
                ('CodigoInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.codigoinforme')),
                ('ConclusionInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.conclusion')),
                ('DoctorInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('EstudioMicroscopicoInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.estudiomicroscopico')),
                ('EvaluacionHormonalInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.evaluacionhormonal')),
                ('FechaPieInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.fechapie')),
                ('HallazgosInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hallazgosnoneoplasicos')),
                ('InflamacionInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.inflamacion')),
                ('LugarInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.lugar')),
                ('MicrorganismosInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.microrganismos')),
                ('MuestraInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.muestra')),
                ('PacienteInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.pacientegenerales')),
                ('RecomendacionInformeCito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.recomendacion')),
            ],
        ),
    ]
