# Generated by Django 4.1.7 on 2023-03-29 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_calidaddemuestra_celescamosas_celglandulares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeAnato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstudioMacroscopicoInformeAnato', models.CharField(default='Sin descripcion', max_length=1000)),
                ('EstudioMicroscopicoInformeAnato', models.CharField(default='Sin descripcion', max_length=1000)),
                ('EspecimenInformeAnato', models.CharField(default='Sin descripcion', max_length=200)),
                ('ConclusionInformeAnato', models.CharField(default='Sin descripcion', max_length=200)),
                ('CodigoInformeAnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.codigoinforme')),
                ('DoctorInformeAnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('FechaPieInformeAnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.fechapie')),
                ('LugarInformeAnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.lugar')),
                ('MuestraInformeAnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.muestra')),
                ('PacienteInformeAnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.pacientegenerales')),
            ],
        ),
    ]
