# Generated by Django 4.1.7 on 2023-04-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_informeanato'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeCito2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstudioMicroscopicoInformeCito2', models.CharField(default='Sin descripcion', max_length=200)),
                ('CalidadDeMuestraInformeCito2', models.CharField(default='Sin descripcion', max_length=200)),
                ('MicrorganismosInformeCito2', models.CharField(default='Sin descripcion', max_length=200)),
                ('HallazgosInformeCito2', models.CharField(default='Sin descripcion', max_length=200)),
                ('CelEscamosasInformeCito2', models.CharField(default='Sin descripcion', max_length=200)),
                ('CelGlandularesInformeCito2', models.CharField(default='Sin descripcion', max_length=100)),
                ('EvaluacionHormonalInformeCito2', models.CharField(default='Sin descripcion', max_length=100)),
                ('InflamacionInformeCito2', models.CharField(default='Sin descripcion', max_length=100)),
                ('ConclusionInformeCito2', models.CharField(default='Sin descripcion', max_length=200)),
                ('OpcionalInformeCito2', models.CharField(default='Sin descripcion', max_length=100)),
                ('RecomendacionInformeCito2', models.CharField(default='Sin descripcion', max_length=1000)),
                ('CodigoInformeCito2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.codigoinforme')),
                ('DoctorInformeAnato2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('FechaPieInformeAnato2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.fechapie')),
                ('LugarInformeAnato2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.lugar')),
                ('MuestraInformeCito2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.muestra')),
                ('PacienteInformeCito2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.pacientegenerales')),
            ],
        ),
    ]
